name: Analyse de sécurité avec Bandit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  bandit-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Installation de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installation de Bandit
        run: pip install bandit

      - name: Lancer l'analyse Bandit et générer un rapport
        id: bandit-analysis
        # Ajout de --exit-zero pour éviter l'échec du job
        # et utilisation du format HTML pour le rapport
        run: bandit -r . -f html -o bandit-report.html --exit-zero
        continue-on-error: true
      
      - name: Uploader le rapport d'analyse
        uses: actions/upload-artifact@v4
        with:
          name: bandit-security-report
          path: bandit-report.html
          retention-days: 5
